# -*- coding: utf-8 -*-
"""validating credit card- Hackerrank problem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TKwl_8Z6ijjwyF-m7Sjs9w7aO_S0lFm9
"""

# Enter your code here. Read input from STDIN. Print output to STDOUT
def checkvalidity(number):
    temp=number.split("-")
    pstr=''.join(temp)
    if number[0] in "456":
        if len(number)==16 or len(number)==19:
            chkstr = "0123456789-"
            for x in number:
                if x not in chkstr:
                    return False
            if len(number) == 19:
                chkstr2 = "0123456789"
            for x in temp:
                if len(x)!=4:
                    return False
            for x in range(len(pstr)-4):
                if pstr[x:x+4] == pstr[x]*4:
                    return False
            return True
    return False
n=int(input())   
for x in range (n):
    if checkvalidity(input()):
        print("Valid")
    else:
        print("Invalid")